<a href="https://colab.research.google.com/github/sowmyasarikonda/AI-ML/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

importing dataset

In [ ]:
dataset=pd.read_csv('preprocessing.csv')
x=dataset.iloc[:,:-1].values #select all the rows and columns except the last column
y=dataset.iloc[:,-1].values #select all the rows and only the last column
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


handling missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean') #fill in the missing values with the mean of all the values
imputer.fit(x[:,1:3]) #Calculating the mean and putting it in the empty cell
x[:,1:3]=imputer.transform(x[:,1:3]) #edit the column
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


encoding independent variable



In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


encoding depedent variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

print(y)

[0 1 0 0 1 1 0 1 0 1]


splitting data into test and training set

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=1)


In [ ]:
print(xtrain)

[[0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(xtest)

[[0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(ytrain)

[0 1 0 0 1 1 0 1]


In [ ]:
print(ytest)

[0 1]


Feature Scalling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.fit_transform(xtest)
print(xtrain)

[[-0.77459667  0.77459667 -0.77459667 -0.57735027  1.29099445 -0.19159184
  -1.07812594]
 [-0.77459667  0.77459667 -0.77459667  1.73205081 -0.77459667 -0.01411729
  -0.07013168]
 [ 1.29099445 -1.29099445  1.29099445 -0.57735027 -0.77459667  0.56670851
   0.63356243]
 [-0.77459667  0.77459667 -0.77459667 -0.57735027  1.29099445 -0.30453019
  -0.30786617]
 [-0.77459667  0.77459667 -0.77459667 -0.57735027  1.29099445 -1.90180114
  -1.42046362]
 [ 1.29099445 -1.29099445  1.29099445 -0.57735027 -0.77459667  1.14753431
   1.23265336]
 [-0.77459667  0.77459667 -0.77459667  1.73205081 -0.77459667  1.43794721
   1.57499104]
 [ 1.29099445 -1.29099445  1.29099445 -0.57735027 -0.77459667 -0.74014954
  -0.56461943]]


In [ ]:
print(xtest)

[[-1.  1. -1.  1.  0. -1. -1.]
 [ 1. -1.  1. -1.  0.  1.  1.]]
